#!/bin/bash

DATE=$(date +"%Y%m%d-%H%M")

make_build(){
	print "Make kernel dtb..." green

		export CROSS_COMPILE=$(pwd)/gcc-arm64/bin/aarch64-elf-
		export CROSS_COMPILE_ARM32=$(pwd)/gcc-arm/bin/arm-eabi-
		make O=out ARCH=arm64 $1
		make -j$(nproc --all) O=out ARCH=arm64

}

make_clean(){
	rm -rf out
}

send_msg(){
	print "${1}" green
	curl -s -X POST https://api.telegram.org/bot"${bot_token}"/sendMessage \
		-d parse_mode="Markdown" \
		-d chat_id="${chat_id}" \
		-d text="${1}"
}

send_file(){
	print "Sending file..." green
	SECONDS=$SECONDS
	let "hours=SECONDS/3600"
	let "minutes=(SECONDS%3600)/60"
	let "seconds=(SECONDS%3600)%60"
	if (( $SECONDS > 3600 )) ; then
	   curl -F chat_id="${chat_id}" \
		-F caption="✅ Time: $hours h $minutes min $seconds second ✅ Last commit: $(git log --pretty=format:'%s' -5)" \
		-F document=@"${1}" \
		 https://api.telegram.org/bot"${bot_token}"/sendDocument 
	elif (( $SECONDS > 60 )) ; then
	   curl -F chat_id="${chat_id}" \
		-F caption="✅ Time: $minutes min $seconds seconds ✅ Last commit: $(git log --pretty=format:'%s' -5)" \
		-F document=@"${1}" \
		 https://api.telegram.org/bot"${bot_token}"/sendDocument
	else
	   curl -F chat_id="${chat_id}" \
		-F caption="✅ Time: $seconds seconds ✅ Last commit: $(git log --pretty=format:'%s' -5)" \
		-F document=@"${1}" \
		 https://api.telegram.org/bot"${bot_token}"/sendDocument
	fi
}

mkzip(){
	print "Generate zip file..." green

	if [ -f $(pwd)/out/arch/arm64/boot/Image.gz-dtb ]; then
		cp $(pwd)/out/arch/arm64/boot/Image.gz-dtb  anykernel/
		cd anykernel
		zip -r9 ../$1 * -x .git README.md *placeholder
		cd ..
		send_file $1
	else
		send_msg "Build Failed !"
		print "Build error !" red
		exit 1
	fi
}

print(){
	echo ""
	case ${2} in
		"red")
		echo -e "\033[31m $1 \033[0m";;
		"green")
		echo -e "\033[32m $1 \033[0m";;
		*)
		echo $1
		;;
	esac
}

gen_toolchain(){
	print "Cloning toolchain files..." green

	git clone --depth=1 https://github.com/mvaisakh/gcc-arm64.git
	git clone --depth=1 https://github.com/mvaisakh/gcc-arm.git

	git clone --depth=1 https://github.com/Peppe289/AnyKernel.git -b begonia  anykernel
}

build(){

	export type="${1} ${2} ${3}"

	make_clean

		make_build "${1}_user_defconfig"

		mkzip "Rave-${1}${2}${3}-$DATE.zip"
}
